// ============================================================================
// Sync and Check Tests
// ============================================================================
//
// Runs sync and check against throwaway repositories.

import assert from 'node:assert/strict';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, test } from 'node:test';

import { check } from '../src/check.mjs';
import { readConfig } from '../src/config.mjs';
import { MARKER_TAG, plan, sync } from '../src/sync.mjs';
import { makeRepo, write } from './repo.mjs';

const BOTH = {
  skills: { 'clean-commit-history': {}, 'clean-comments': {} },
};

/**
 * Finds one planned file's content by the end of its path.
 *
 * @param root - The repository root
 * @param suffix - The end of the file's path
 * @returns The rendered content
 */
async function planned(root, suffix) {
  return (await plan(root)).find((file) => file.path.endsWith(suffix)).content;
}

describe('readConfig', () => {
  test('throws when there is no config', () => {
    assert.throws(() => readConfig(makeRepo()), /No \.devkit\/skills\.json/);
  });

  test('rejects an unknown skill, naming the ones that exist', () => {
    const root = makeRepo({ 'skills.json': { skills: { nope: {} } } });

    assert.throws(
      () => readConfig(root),
      /Unknown skill "nope".*clean-comments/,
    );
  });

  test('rejects an unknown option', () => {
    const root = makeRepo({
      'skills.json': { skills: { 'clean-comments': { typo: 1 } } },
    });

    assert.throws(() => readConfig(root), /Unknown option "typo"/);
  });

  test('rejects an unknown shared setting', () => {
    const root = makeRepo({ 'skills.json': { skilsDir: 'x', skills: {} } });

    assert.throws(() => readConfig(root), /Unknown setting "skilsDir"/);
  });
});

describe('plan', () => {
  test('leaves no placeholder unfilled', async () => {
    for (const { path, content } of await plan(
      makeRepo({ 'skills.json': BOTH }),
    )) {
      assert.doesNotMatch(content, /\{\{/, path);
    }
  });

  test('puts the marker in every file, after the frontmatter', async () => {
    for (const { content } of await plan(makeRepo({ 'skills.json': BOTH }))) {
      assert.match(content, /^---\n[\s\S]*?\n---\n\n<!-- Generated by/);
    }
  });

  test('writes the agent alongside clean-comments', async () => {
    const paths = (await plan(makeRepo({ 'skills.json': BOTH }))).map(
      (file) => file.path,
    );

    assert.deepEqual(paths.sort(), [
      '.claude/agents/comments-specialist.md',
      '.claude/skills/clean-comments/SKILL.md',
      '.claude/skills/clean-commit-history/SKILL.md',
    ]);
  });

  test('honours skillsDir, agentsDir and baseBranch', async () => {
    const root = makeRepo({
      'skills.json': {
        ...BOTH,
        skillsDir: '.agents/skills',
        agentsDir: 'agents',
        baseBranch: 'trunk',
      },
    });
    const files = await plan(root);

    assert.ok(files.some((f) => f.path === 'agents/comments-specialist.md'));
    assert.ok(
      files
        .filter((f) => f.path.startsWith('.agents/skills/'))
        .every((f) => f.content.includes('trunk')),
    );
  });

  test('reads the comment contract path from terse.json', async () => {
    const root = makeRepo({
      'skills.json': BOTH,
      'terse.json': { rulesDoc: 'docs/comments.md' },
    });

    for (const { path, content } of await plan(root)) {
      if (path.includes('comment')) assert.match(content, /docs\/comments\.md/);
    }
  });

  test('falls back to the terse-docs default when rulesDoc is unset', async () => {
    const root = makeRepo({ 'skills.json': BOTH });

    assert.match(
      await planned(root, 'clean-comments/SKILL.md'),
      /\.devkit\/comment-rules\.md/,
    );
  });

  test('drops the typecheck step unless one is configured', async () => {
    const without = makeRepo({ 'skills.json': BOTH });
    assert.doesNotMatch(
      await planned(without, 'clean-comments/SKILL.md'),
      /Typecheck/,
    );

    const withTypecheck = makeRepo({
      'skills.json': {
        skills: { 'clean-comments': { typecheck: 'npm run typecheck' } },
      },
    });
    assert.match(
      await planned(withTypecheck, 'clean-comments/SKILL.md'),
      /Typecheck[\s\S]*npm run typecheck/,
    );
  });

  test('loads every preload skill in the skill and the agent', async () => {
    const root = makeRepo({
      'skills.json': {
        skills: {
          'clean-comments': { preloadSkills: ['comments', 'readability'] },
        },
      },
    });

    assert.match(
      await planned(root, 'clean-comments/SKILL.md'),
      /Skill\(skill: "readability"\)/,
    );
    assert.match(
      await planned(root, 'comments-specialist.md'),
      /skills:\n {2}- comments\n {2}- readability\n---/,
    );
  });

  test('points at commitRules when set, and a fallback when not', async () => {
    const withRules = makeRepo({
      'skills.json': {
        skills: { 'clean-commit-history': { commitRules: 'rules/commits.md' } },
      },
    });
    const ruled = await planned(withRules, 'SKILL.md');
    assert.match(ruled, /`rules\/commits\.md`/);
    assert.doesNotMatch(ruled, /Conventional Commits/);

    const without = makeRepo({
      'skills.json': { skills: { 'clean-commit-history': {} } },
    });
    assert.match(await planned(without, 'SKILL.md'), /Conventional Commits/);
  });
});

describe('sync and check', () => {
  test('check passes straight after sync', async () => {
    const root = makeRepo({ 'skills.json': BOTH });
    await sync(root);

    assert.deepEqual(await check(root), []);
  });

  test('a second sync changes nothing', async () => {
    const root = makeRepo({ 'skills.json': BOTH });
    await sync(root);

    assert.deepEqual((await sync(root)).written, []);
  });

  test('check reports a missing file', async () => {
    const problems = await check(makeRepo({ 'skills.json': BOTH }));

    assert.equal(problems.length, 3);
    assert.ok(problems.every((p) => p.problem === 'missing'));
  });

  test('check reports a hand edit', async () => {
    const root = makeRepo({ 'skills.json': BOTH });
    await sync(root);

    const path = join(root, '.claude/skills/clean-comments/SKILL.md');
    writeFileSync(path, `${readFileSync(path, 'utf8')}\nextra\n`);

    assert.deepEqual(await check(root), [
      {
        path: '.claude/skills/clean-comments/SKILL.md',
        problem: 'out of date or edited by hand',
      },
    ]);
  });

  test('refuses to overwrite a hand-written skill, and writes nothing', async () => {
    const root = makeRepo({ 'skills.json': BOTH });
    write(root, '.claude/skills/clean-comments/SKILL.md', 'mine');

    await assert.rejects(() => sync(root), /clean-comments\/SKILL\.md/);
    assert.equal(existsSync(join(root, '.claude/agents')), false);
  });

  test('overwrites a hand-written skill with --force', async () => {
    const root = makeRepo({ 'skills.json': BOTH });
    write(root, '.claude/skills/clean-comments/SKILL.md', 'mine');

    await sync(root, { force: true });

    assert.deepEqual(await check(root), []);
  });

  test('removes a generated skill the config no longer names', async () => {
    const root = makeRepo({ 'skills.json': BOTH });
    await sync(root);

    writeFileSync(
      join(root, '.devkit/skills.json'),
      JSON.stringify({ skills: { 'clean-commit-history': {} } }),
    );

    assert.deepEqual(
      (await check(root)).map((p) => p.problem),
      ['no longer in the config', 'no longer in the config'],
    );

    const { removed } = await sync(root);

    assert.equal(removed.length, 2);
    assert.equal(
      existsSync(join(root, '.claude/skills/clean-comments')),
      false,
    );
    assert.deepEqual(await check(root), []);
  });

  test('leaves hand-written skills beside the generated ones alone', async () => {
    const root = makeRepo({ 'skills.json': BOTH });
    write(root, '.claude/skills/comments/SKILL.md', 'mine');
    write(root, '.claude/agents/other.md', 'mine');

    await sync(root);
    writeFileSync(
      join(root, '.devkit/skills.json'),
      JSON.stringify({ skills: {} }),
    );
    await sync(root);

    assert.equal(
      readFileSync(join(root, '.claude/skills/comments/SKILL.md'), 'utf8'),
      'mine',
    );
    assert.ok(
      !readFileSync(join(root, '.claude/agents/other.md'), 'utf8').includes(
        MARKER_TAG,
      ),
    );
  });
});
