// ============================================================================
// Sync and Check Tests
// ============================================================================
//
// Runs sync and check against throwaway repositories.

import assert from 'node:assert/strict';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { describe, test } from 'node:test';

import { check } from '../src/check.mjs';
import { readConfig } from '../src/config.mjs';
import { MARKER_TAG, plan, sync } from '../src/sync.mjs';

/**
 * Makes an empty repository root holding the given `.devkit` files.
 *
 * @param devkit - File contents by name, objects written as JSON
 * @returns The root's absolute path
 */
function makeRepo(devkit = {}) {
  const root = mkdtempSync(join(tmpdir(), 'skills-'));
  mkdirSync(join(root, '.git'));
  mkdirSync(join(root, '.devkit'));

  for (const [name, body] of Object.entries(devkit)) {
    writeFileSync(join(root, '.devkit', name), JSON.stringify(body));
  }

  return root;
}

/**
 * Writes a file under a root, creating its directories.
 *
 * @param root - The repository root
 * @param path - Path relative to the root
 * @param content - The file's text
 */
function write(root, path, content) {
  mkdirSync(dirname(join(root, path)), { recursive: true });
  writeFileSync(join(root, path), content);
}

const BOTH = {
  skills: { 'clean-commit-history': {}, 'clean-comments': {} },
};

describe('readConfig', () => {
  test('throws when there is no config', () => {
    assert.throws(() => readConfig(makeRepo()), /No \.devkit\/skills\.json/);
  });

  test('rejects an unknown skill, naming the ones that exist', () => {
    const root = makeRepo({ 'skills.json': { skills: { nope: {} } } });

    assert.throws(
      () => readConfig(root),
      /Unknown skill "nope".*clean-comments/,
    );
  });

  test('rejects an unknown option', () => {
    const root = makeRepo({
      'skills.json': { skills: { 'clean-comments': { typo: 1 } } },
    });

    assert.throws(() => readConfig(root), /Unknown option "typo"/);
  });

  test('rejects an unknown shared setting', () => {
    const root = makeRepo({ 'skills.json': { skilsDir: 'x', skills: {} } });

    assert.throws(() => readConfig(root), /Unknown setting "skilsDir"/);
  });
});

describe('plan', () => {
  test('leaves no placeholder unfilled', () => {
    for (const { path, content } of plan(makeRepo({ 'skills.json': BOTH }))) {
      assert.doesNotMatch(content, /\{\{/, path);
    }
  });

  test('puts the marker in every file, after the frontmatter', () => {
    for (const { content } of plan(makeRepo({ 'skills.json': BOTH }))) {
      assert.match(content, /^---\n[\s\S]*?\n---\n\n<!-- Generated by/);
    }
  });

  test('writes the agent alongside clean-comments', () => {
    const paths = plan(makeRepo({ 'skills.json': BOTH })).map((f) => f.path);

    assert.deepEqual(paths.sort(), [
      '.claude/agents/comments-specialist.md',
      '.claude/skills/clean-comments/SKILL.md',
      '.claude/skills/clean-commit-history/SKILL.md',
    ]);
  });

  test('honours skillsDir, agentsDir and baseBranch', () => {
    const root = makeRepo({
      'skills.json': {
        ...BOTH,
        skillsDir: '.agents/skills',
        agentsDir: 'agents',
        baseBranch: 'trunk',
      },
    });
    const files = plan(root);

    assert.ok(files.some((f) => f.path === 'agents/comments-specialist.md'));
    assert.ok(
      files
        .filter((f) => f.path.startsWith('.agents/skills/'))
        .every((f) => f.content.includes('trunk')),
    );
  });

  test('reads the comment contract path from terse.json', () => {
    const root = makeRepo({
      'skills.json': BOTH,
      'terse.json': { rulesDoc: 'docs/comments.md' },
    });

    for (const { path, content } of plan(root)) {
      if (path.includes('comment')) assert.match(content, /docs\/comments\.md/);
    }
  });

  test('falls back to the terse-docs default when rulesDoc is unset', () => {
    const skill = plan(makeRepo({ 'skills.json': BOTH })).find((f) =>
      f.path.endsWith('clean-comments/SKILL.md'),
    );

    assert.match(skill.content, /\.devkit\/comment-rules\.md/);
  });

  test('drops the typecheck step unless one is configured', () => {
    const find = (root) =>
      plan(root).find((f) => f.path.endsWith('clean-comments/SKILL.md'))
        .content;

    assert.doesNotMatch(find(makeRepo({ 'skills.json': BOTH })), /Typecheck/);

    const withTypecheck = makeRepo({
      'skills.json': {
        skills: { 'clean-comments': { typecheck: 'npm run typecheck' } },
      },
    });
    assert.match(find(withTypecheck), /Typecheck[\s\S]*npm run typecheck/);
  });

  test('loads every preload skill in the skill and the agent', () => {
    const root = makeRepo({
      'skills.json': {
        skills: {
          'clean-comments': { preloadSkills: ['comments', 'readability'] },
        },
      },
    });
    const [skill, agent] = plan(root);

    assert.match(skill.content, /Skill\(skill: "readability"\)/);
    assert.match(
      agent.content,
      /skills:\n {2}- comments\n {2}- readability\n---/,
    );
  });

  test('points at commitRules when set, and a fallback when not', () => {
    const find = (root) => plan(root)[0].content;

    const withRules = makeRepo({
      'skills.json': {
        skills: { 'clean-commit-history': { commitRules: 'rules/commits.md' } },
      },
    });
    assert.match(find(withRules), /`rules\/commits\.md`/);
    assert.doesNotMatch(find(withRules), /Conventional Commits/);

    const without = makeRepo({
      'skills.json': { skills: { 'clean-commit-history': {} } },
    });
    assert.match(find(without), /Conventional Commits/);
  });
});

describe('sync and check', () => {
  test('check passes straight after sync', () => {
    const root = makeRepo({ 'skills.json': BOTH });
    sync(root);

    assert.deepEqual(check(root), []);
  });

  test('a second sync changes nothing', () => {
    const root = makeRepo({ 'skills.json': BOTH });
    sync(root);

    assert.deepEqual(sync(root).written, []);
  });

  test('check reports a missing file', () => {
    const root = makeRepo({ 'skills.json': BOTH });

    assert.equal(check(root).length, 3);
    assert.ok(check(root).every((p) => p.problem === 'missing'));
  });

  test('check reports a hand edit', () => {
    const root = makeRepo({ 'skills.json': BOTH });
    sync(root);

    const path = join(root, '.claude/skills/clean-comments/SKILL.md');
    writeFileSync(path, `${readFileSync(path, 'utf8')}\nextra\n`);

    assert.deepEqual(check(root), [
      {
        path: '.claude/skills/clean-comments/SKILL.md',
        problem: 'out of date or edited by hand',
      },
    ]);
  });

  test('refuses to overwrite a hand-written skill, and writes nothing', () => {
    const root = makeRepo({ 'skills.json': BOTH });
    write(root, '.claude/skills/clean-comments/SKILL.md', 'mine');

    assert.throws(() => sync(root), /clean-comments\/SKILL\.md/);
    assert.equal(existsSync(join(root, '.claude/agents')), false);
  });

  test('overwrites a hand-written skill with --force', () => {
    const root = makeRepo({ 'skills.json': BOTH });
    write(root, '.claude/skills/clean-comments/SKILL.md', 'mine');

    sync(root, { force: true });

    assert.deepEqual(check(root), []);
  });

  test('removes a generated skill the config no longer names', () => {
    const root = makeRepo({ 'skills.json': BOTH });
    sync(root);

    writeFileSync(
      join(root, '.devkit/skills.json'),
      JSON.stringify({ skills: { 'clean-commit-history': {} } }),
    );

    assert.deepEqual(
      check(root).map((p) => p.problem),
      ['no longer in the config', 'no longer in the config'],
    );

    const { removed } = sync(root);

    assert.equal(removed.length, 2);
    assert.equal(
      existsSync(join(root, '.claude/skills/clean-comments')),
      false,
    );
    assert.deepEqual(check(root), []);
  });

  test('leaves hand-written skills beside the generated ones alone', () => {
    const root = makeRepo({ 'skills.json': BOTH });
    write(root, '.claude/skills/comments/SKILL.md', 'mine');
    write(root, '.claude/agents/other.md', 'mine');

    sync(root);
    writeFileSync(
      join(root, '.devkit/skills.json'),
      JSON.stringify({ skills: {} }),
    );
    sync(root);

    assert.equal(
      readFileSync(join(root, '.claude/skills/comments/SKILL.md'), 'utf8'),
      'mine',
    );
    assert.ok(existsSync(join(root, '.claude/agents/other.md')));
    assert.ok(
      !readFileSync(join(root, '.claude/agents/other.md'), 'utf8').includes(
        MARKER_TAG,
      ),
    );
  });
});
