// ============================================================================
// Config
// ============================================================================
//
// Reads and validates `.devkit/dead-code.json`: the project folder, the
// workspaces, the issue types and the known false positives, each with its
// reason. Files @euanmsm/skills generated are known without an entry.

import { closeSync, openSync, readSync } from 'node:fs';
import { join } from 'node:path';

import { loadConfig, repoRoot } from '@euanmsm/devkit-core';

/** The config file's name inside `.devkit/`. */
export const CONFIG_NAME = 'dead-code.json';

/** Text @euanmsm/skills writes at the head of every file it generates. */
const GENERATED_TAG = 'Generated by @euanmsm/skills';

/** How a line holding the marker starts: a comment opener, then the tag. */
const GENERATED_STARTS = ['<!-- ', '// ', '# '].map(
  (opener) => opener + GENERATED_TAG,
);

/** The reason a finding in a generated file is known. */
const GENERATED_REASON =
  'generated by @euanmsm/skills, and loaded by a tool by its path rather than imported';

/** Values used for any key the config leaves out. */
export const DEFAULTS = {
  directory: null,
  workspaces: [],
  include: ['files', 'exports', 'types'],
};

/** Knip's issue types, the values `include` accepts. */
export const ISSUE_TYPES = [
  'files',
  'dependencies',
  'devDependencies',
  'optionalPeerDependencies',
  'unlisted',
  'binaries',
  'unresolved',
  'exports',
  'nsExports',
  'types',
  'nsTypes',
  'enumMembers',
  'namespaceMembers',
  'duplicates',
  'catalog',
  'catalogReferences',
  'cycles',
];

const TOP_KEYS = new Set(['directory', 'workspaces', 'include', 'known']);
const KNOWN_KEYS = new Set(['path', 'names', 'reason']);

/**
 * Tells whether a value is a list of strings.
 *
 * @param value - Anything from the parsed JSON
 * @returns True for an array holding only strings
 */
function isStringList(value) {
  return Array.isArray(value) && value.every((v) => typeof v === 'string');
}

/**
 * Throws when an object carries a key outside the allowed set.
 *
 * @param object - The object to check
 * @param allowed - The keys it may carry
 * @param where - Prefix naming the object in the error
 * @throws When a key is neither allowed nor a `_` note
 */
function rejectUnknownKeys(object, allowed, where) {
  for (const key of Object.keys(object))
    if (!allowed.has(key) && !key.startsWith('_'))
      throw new Error(`${where}: unknown key "${key}"`);
}

/**
 * Checks a list of knip issue types.
 *
 * @param include - The types, as given
 * @param where - Names the list in errors
 * @returns The same list
 * @throws When it is empty or holds a name knip does not know
 */
export function checkInclude(include, where) {
  if (include.length === 0)
    throw new Error(`${where} must name at least one knip issue type`);

  for (const type of include) {
    if (ISSUE_TYPES.includes(type)) continue;
    const near = ISSUE_TYPES.find((t) => t === `${type}s` || t === `${type}es`);
    throw new Error(
      `${where}: "${type}" is not a knip issue type${near ? `. Did you mean "${near}"?` : ''} Use any of ${ISSUE_TYPES.join(', ')}.`,
    );
  }

  return include;
}

/**
 * Validates one `known` entry and compiles its path.
 *
 * @param entry - The entry as parsed
 * @param where - Prefix naming the entry in errors
 * @returns `{ path, pattern, names, reason }`, with `names` null when absent
 * @throws When the entry is malformed
 */
function knownEntry(entry, where) {
  if (!entry || typeof entry !== 'object' || Array.isArray(entry))
    throw new Error(`${where} must be an object`);
  rejectUnknownKeys(entry, KNOWN_KEYS, where);

  if (typeof entry.path !== 'string' || entry.path === '')
    throw new Error(`${where}.path is required, as a regex string`);
  let pattern;
  try {
    pattern = new RegExp(entry.path);
  } catch (error) {
    throw new Error(`${where}.path is not a valid regex: ${error.message}`);
  }

  if (entry.names !== undefined && !isStringList(entry.names))
    throw new Error(`${where}.names must be a list of strings`);
  if (entry.names?.length === 0)
    throw new Error(
      `${where}.names is empty, so it matches nothing. Leave it out to match every name`,
    );
  if (typeof entry.reason !== 'string' || entry.reason.trim() === '')
    throw new Error(`${where}.reason is required`);

  return {
    path: entry.path,
    pattern,
    names: entry.names ?? null,
    reason: entry.reason,
  };
}

/**
 * Checks a parsed config and fills the defaults.
 *
 * @param raw - The parsed JSON, or null when there is no file
 * @param source - The file's name, used to prefix every error
 * @returns `{ directory, workspaces, include, known }`
 * @throws When a key is unknown, mistyped or missing
 */
export function validate(raw, source) {
  const config = raw ?? {};
  if (typeof config !== 'object' || Array.isArray(config))
    throw new Error(`${source} must hold a JSON object`);
  rejectUnknownKeys(config, TOP_KEYS, source);

  if (
    config.directory !== undefined &&
    (typeof config.directory !== 'string' || config.directory.trim() === '')
  )
    throw new Error(
      `${source}: directory must be a folder path, relative to the repository root`,
    );
  for (const key of ['workspaces', 'include'])
    if (config[key] !== undefined && !isStringList(config[key]))
      throw new Error(`${source}: ${key} must be a list of strings`);
  if (config.include !== undefined)
    checkInclude(config.include, `${source}: include`);
  if (config.known !== undefined && !Array.isArray(config.known))
    throw new Error(`${source}: known must be a list`);

  return {
    directory: config.directory ?? DEFAULTS.directory,
    workspaces: config.workspaces ?? DEFAULTS.workspaces,
    include: config.include ?? DEFAULTS.include,
    known: (config.known ?? []).map((entry, i) =>
      knownEntry(entry, `${source}: known[${i}]`),
    ),
  };
}

/**
 * Tells whether a known entry covers a finding.
 *
 * @param entry - A validated `known` entry
 * @param finding - A finding
 * @returns True when the path matches and the name is listed, or no names are
 */
function covers(entry, finding) {
  return (
    entry.pattern.test(finding.file) &&
    (!entry.names || entry.names.includes(finding.name))
  );
}

/**
 * Sets the findings a `known` entry covers apart from the rest, each taking the
 * first covering entry's reason while every covering entry counts as used, and
 * lists as stale the entries, or the `names` in them, that matched nothing.
 *
 * @param findings - Findings from knip
 * @param known - The config's validated `known` entries
 * @returns `{ findings, known, stale }`, known findings carrying the reason
 */
export function applyKnown(findings, known) {
  const kept = [];
  const set = [];
  const hit = new Map(known.map((k) => [k, new Set()]));

  for (const finding of findings) {
    const entries = known.filter((k) => covers(k, finding));
    if (entries.length === 0) {
      kept.push(finding);
      continue;
    }
    for (const entry of entries) hit.get(entry).add(finding.name);
    set.push({ ...finding, reason: entries[0].reason });
  }

  const stale = [];
  for (const entry of known) {
    const { path, names, reason } = entry;
    const seen = hit.get(entry);
    if (seen.size === 0) {
      stale.push({ path, ...(names ? { names } : {}), reason });
      continue;
    }
    const unseen = (names ?? []).filter((n) => !seen.has(n));
    if (unseen.length) stale.push({ path, names: unseen, reason });
  }

  return { findings: kept, known: set, stale };
}

/**
 * Sets apart the findings in files @euanmsm/skills generated, such as a skill's
 * workflow script, which a tool loads by its path so knip never sees imported.
 *
 * @param findings - Findings from knip
 * @param root - The git root the findings' paths are relative to
 * @returns `{ findings, known }`, known findings carrying the reason
 */
export function applyGenerated(findings, root) {
  const heads = new Map();
  const generated = (file) => {
    if (!heads.has(file))
      heads.set(
        file,
        head(join(root, file))
          .split(/\r?\n/)
          .some((line) => GENERATED_STARTS.some((s) => line.startsWith(s))),
      );
    return heads.get(file);
  };

  const kept = [];
  const known = [];
  for (const finding of findings) {
    if (generated(finding.file))
      known.push({ ...finding, reason: GENERATED_REASON });
    else kept.push(finding);
  }
  return { findings: kept, known };
}

/**
 * Reads the start of a file, where a generated marker sits.
 *
 * @param path - Absolute path to the file
 * @returns Its first 2 KB as text, empty when it cannot be read
 */
function head(path) {
  let fd;
  try {
    fd = openSync(path, 'r');
    const buffer = Buffer.alloc(2048);
    return buffer.toString('utf8', 0, readSync(fd, buffer, 0, 2048, 0));
  } catch {
    return '';
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

/**
 * Reads the repository's config.
 *
 * @param root - The repository root
 * @returns The validated config, defaults filled
 * @throws When the file does not parse or validate
 */
export function readConfig(root = repoRoot()) {
  return validate(
    loadConfig(CONFIG_NAME, null, root),
    `.devkit/${CONFIG_NAME}`,
  );
}
