// ============================================================================
// Check
// ============================================================================
//
// Compares the skills on disk with what sync would write, so CI can fail a
// branch whose generated skills were edited by hand or not regenerated.

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { generatedOnDisk, isGenerated, plan } from './sync.mjs';

/**
 * Lists every way the skills on disk differ from the config.
 *
 * @param root - The repository root
 * @returns One `{ path, problem }` per mismatch, empty when in step
 */
export async function check(root) {
  const files = await plan(root);
  const problems = [];

  for (const { path, content } of files) {
    const target = join(root, path);

    if (!existsSync(target)) {
      problems.push({ path, problem: 'missing' });
    } else if (!isGenerated(target)) {
      problems.push({ path, problem: 'not generated by skills sync' });
    } else if (readFileSync(target, 'utf8') !== content) {
      problems.push({ path, problem: 'out of date or edited by hand' });
    }
  }

  const planned = new Set(files.map(({ path }) => path));

  for (const path of generatedOnDisk(root)) {
    if (!planned.has(path)) {
      problems.push({ path, problem: 'no longer in the config' });
    }
  }

  return problems;
}
