// ============================================================================
// Sync
// ============================================================================
//
// Writes every enabled skill into the repository and removes generated skills
// the config does not name. A file without the generated marker is never
// overwritten or deleted unless forced.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  rmdirSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { readConfig } from './config.mjs';
import { render } from './render.mjs';
import { toSource } from './review/serialise.mjs';
import { SKILLS } from './skills.mjs';

const TEMPLATES = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'templates',
);

/** Text every generated file carries, which is how sync recognises its own. */
export const MARKER_TAG = 'Generated by @euanmsm/skills';

const MARKER_TEXT = `${MARKER_TAG} from .devkit/skills.json. Edit that, then run \`npx --no-install skills sync\`.`;

const MARKER = `<!-- ${MARKER_TEXT} -->`;

const SCRIPT_MARKER = `// ${MARKER_TEXT}`;

const YAML_MARKER = `# ${MARKER_TEXT}`;

/** How each kind of marker line starts; the wording after the tag changes between releases. */
const MARKER_STARTS = [MARKER, SCRIPT_MARKER, YAML_MARKER].map((marker) =>
  marker.slice(0, marker.indexOf(MARKER_TAG) + MARKER_TAG.length),
);

/** Where the generated GitHub workflows live. */
const WORKFLOWS_DIR = '.github/workflows';

/**
 * Renders every file the config asks for, without touching the disk.
 *
 * @param root - The repository root
 * @returns One `{ path, content, seed }` per file, `path` relative to the root; a `seed` file is written only when missing and belongs to the repository afterwards
 */
export async function plan(root) {
  const config = readConfig(root);
  const files = [];

  for (const [name, options] of Object.entries(config.skills)) {
    const skill = SKILLS[name];
    const values = {
      marker: MARKER,
      markerText: MARKER_TEXT,
      baseBranch: config.baseBranch,
      ...(await skill.values(options, root, config)),
    };
    const entries =
      typeof skill.files === 'function'
        ? skill.files(options, values)
        : skill.files;

    for (const file of entries) {
      const template = readFileSync(join(TEMPLATES, file.template), 'utf8');
      files.push({
        path: file.dir ? join(config[file.dir], file.path) : file.path,
        content: file.engine
          ? renderEngine(template, values[file.engine])
          : render(template, values),
        seed: Boolean(file.seed),
      });
    }
  }

  return files;
}

/**
 * Fills a workflow template with the skill name and resolved config.
 *
 * @param template - The engine template's text
 * @param config - The resolved config, carrying the skill's `name`
 * @returns The workflow script
 */
export function renderEngine(template, config) {
  // Replacer functions, since a `$` in the config would read as a pattern.
  const script = template
    .replace("'__SKILL_NAME__'", () => JSON.stringify(config.name))
    .replace('/* CONFIG */ null', () => toSource(config));

  return `${SCRIPT_MARKER}\n${script}`;
}

/**
 * Lists the generated files already on disk in the configured directories and `.github/workflows`.
 *
 * @param root - The repository root
 * @returns Repo-relative paths of every file carrying the marker
 */
export function generatedOnDisk(root) {
  const { skillsDir, agentsDir, rulesDir } = readConfig(root);
  const candidates = [];

  for (const entry of listDir(join(root, skillsDir))) {
    for (const file of listDir(join(root, skillsDir, entry))) {
      candidates.push(join(skillsDir, entry, file));
    }
  }
  for (const dir of [agentsDir, rulesDir]) {
    for (const entry of listDir(join(root, dir))) {
      if (entry.endsWith('.md')) candidates.push(join(dir, entry));
    }
  }
  for (const entry of listDir(join(root, WORKFLOWS_DIR))) {
    if (/\.ya?ml$/.test(entry)) candidates.push(join(WORKFLOWS_DIR, entry));
  }

  return candidates.filter((path) => isGenerated(join(root, path)));
}

/**
 * Tells whether a file exists and carries the generated marker where sync writes it.
 *
 * @param path - Absolute path to the file
 * @returns Whether sync wrote it
 */
export function isGenerated(path) {
  if (!existsSync(path)) return false;

  try {
    const line = markerLine(readFileSync(path, 'utf8'));
    return MARKER_STARTS.some((start) => line.startsWith(start));
  } catch {
    return false;
  }
}

/**
 * Finds the line sync puts its marker on: the first, or the first after markdown frontmatter.
 *
 * @param content - The file's text
 * @returns That line, empty when there is none
 */
function markerLine(content) {
  const lines = content.split('\n');
  if (lines[0] !== '---') return lines[0];

  const close = lines.indexOf('---', 1);
  if (close === -1) return '';
  return lines.slice(close + 1).find((line) => line !== '') ?? '';
}

/**
 * Lists a directory's entries, or nothing when it does not exist.
 *
 * @param dir - Absolute path to the directory
 * @returns The entry names
 */
function listDir(dir) {
  return existsSync(dir) && statSync(dir).isDirectory() ? readdirSync(dir) : [];
}

/**
 * Writes the planned files and removes generated ones outside the plan.
 *
 * @param root - The repository root
 * @param options - `force` overwrites files that were not generated
 * @returns Repo-relative paths `written`, `unchanged` and `removed`
 * @throws When a planned path holds a hand-written file and `force` is off
 */
export async function sync(root, { force = false } = {}) {
  const files = await plan(root);

  const handWritten = files.filter(
    ({ path, seed }) =>
      !seed && existsSync(join(root, path)) && !isGenerated(join(root, path)),
  );
  if (handWritten.length > 0 && !force) {
    throw new Error(
      `These files were not written by skills sync, so it will not overwrite them:\n${handWritten
        .map(({ path }) => `  ${path}`)
        .join('\n')}\nDelete them, or pass --force to replace them.`,
    );
  }

  const result = { written: [], unchanged: [], removed: [] };

  for (const { path, content, seed } of files) {
    const target = join(root, path);

    if (
      existsSync(target) &&
      (seed || readFileSync(target, 'utf8') === content)
    ) {
      result.unchanged.push(path);
      continue;
    }

    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
    result.written.push(path);
  }

  const planned = new Set(files.map(({ path }) => path));

  for (const path of generatedOnDisk(root)) {
    if (planned.has(path)) continue;

    rmSync(join(root, path));
    result.removed.push(path);

    const dir = dirname(join(root, path));
    const { skillsDir } = readConfig(root);
    if (
      dirname(dir) === join(root, skillsDir) &&
      readdirSync(dir).length === 0
    ) {
      rmdirSync(dir);
    }
  }

  return result;
}
