// ============================================================================
// Sync
// ============================================================================
//
// Writes every enabled skill into the repository and removes generated skills
// the config does not name. A file without the generated marker is never
// overwritten or deleted unless forced.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  rmdirSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { CONFIG_NAME, readConfig } from './config.mjs';
import { render } from './render.mjs';
import { installedPackages } from './review/config.mjs';
import { toSource } from './review/serialise.mjs';
import { SKILLS } from './skills.mjs';

const TEMPLATES = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'templates',
);

/** Text every generated file carries, which is how sync recognises its own. */
export const MARKER_TAG = 'Generated by @euanmsm/skills';

/**
 * The marker's wording, naming every config file the skill's content comes from.
 *
 * @param source - The skill's own config file, when it has one
 * @returns The text after the comment opener
 */
function markerText(source) {
  const from = source
    ? `.devkit/${CONFIG_NAME} and ${source}. Edit those`
    : `.devkit/${CONFIG_NAME}. Edit that`;
  return `${MARKER_TAG} from ${from}, then run \`npx --no-install skills sync\`.`;
}

/** How each kind of marker line starts; the wording after the tag changes between releases. */
const MARKER_STARTS = ['<!-- ', '// ', '# '].map(
  (opener) => opener + MARKER_TAG,
);

/** Where the generated GitHub workflows live. */
const WORKFLOWS_DIR = '.github/workflows';

/**
 * Renders every file the config asks for, without touching the disk.
 *
 * @param root - The repository root
 * @param config - The config from `readConfig`, read afresh when not given
 * @returns One `{ path, content, seed }` per file, `path` relative to the root; a `seed` file is written only when missing and belongs to the repository afterwards
 * @throws When two skills would write the same file
 */
export async function plan(root, config = readConfig(root)) {
  const files = [];
  const owners = new Map();
  const format = config.format === 'prettier' ? await prettierFor(root) : null;

  for (const [name, options] of Object.entries(config.skills)) {
    const skill = SKILLS[name];
    const text = markerText(options.config);
    const values = {
      marker: `<!-- ${text} -->`,
      markerText: text,
      baseBranch: config.baseBranch,
      ...(await skill.values(options, root, config)),
    };
    const entries =
      typeof skill.files === 'function'
        ? skill.files(options, values)
        : skill.files;

    for (const file of entries) {
      const path = file.dir ? join(config[file.dir], file.path) : file.path;
      if (owners.has(path)) {
        throw new Error(
          `Skills "${owners.get(path)}" and "${name}" in .devkit/${CONFIG_NAME} both write ${path}`,
        );
      }
      owners.set(path, name);

      const template = readFileSync(join(TEMPLATES, file.template), 'utf8');
      const content = file.engine
        ? renderEngine(template, values[file.engine], text)
        : render(template, values);
      files.push({
        path,
        content: format ? await format(path, content) : content,
        seed: Boolean(file.seed),
      });
    }
  }

  return files;
}

/**
 * Loads the repository's own Prettier, to format files the way its commits will.
 *
 * @param root - The repository root
 * @returns A function formatting one file's text by its repo-relative path, leaving a file Prettier ignores or has no parser for as it is
 * @throws When the repository does not depend on Prettier
 */
async function prettierFor(root) {
  let entry;
  try {
    entry = createRequire(join(root, 'package.json')).resolve('prettier');
  } catch {
    throw new Error(
      `"format": "prettier" in .devkit/${CONFIG_NAME} needs Prettier installed in this repository: npm i -D prettier`,
    );
  }
  const loaded = await import(pathToFileURL(entry).href);
  const prettier = loaded.default ?? loaded;
  const ignorePath = join(root, '.prettierignore');

  return async (path, content) => {
    const filepath = join(root, path);
    const info = await prettier.getFileInfo(filepath, { ignorePath });
    if (info.ignored || !info.inferredParser) return content;

    const options = await prettier.resolveConfig(filepath);
    return prettier.format(content, { ...options, filepath });
  };
}

/**
 * Fills a workflow template with the skill name and resolved config.
 *
 * @param template - The engine template's text
 * @param config - The resolved config, carrying the skill's `name`
 * @param text - The marker's wording, naming only skills.json when not given
 * @returns The workflow script
 */
export function renderEngine(template, config, text = markerText()) {
  // Replacer functions, since a `$` in the config would read as a pattern.
  const script = template
    .replace("'__SKILL_NAME__'", () => JSON.stringify(config.name))
    .replace('/* CONFIG */ null', () => toSource(config));

  return `// ${text}\n${script}`;
}

/**
 * Lists the generated files already on disk in the configured directories and `.github/workflows`.
 *
 * @param root - The repository root
 * @param config - The config from `readConfig`, read afresh when not given
 * @returns Repo-relative paths of every file carrying the marker
 */
export function generatedOnDisk(root, config = readConfig(root)) {
  const { skillsDir, agentsDir, rulesDir } = config;
  const candidates = [];

  for (const entry of listDir(join(root, skillsDir))) {
    for (const file of listDir(join(root, skillsDir, entry))) {
      candidates.push(join(skillsDir, entry, file));
    }
  }
  for (const dir of [agentsDir, rulesDir]) {
    for (const entry of listDir(join(root, dir))) {
      if (entry.endsWith('.md')) candidates.push(join(dir, entry));
    }
  }
  for (const entry of listDir(join(root, WORKFLOWS_DIR))) {
    if (/\.ya?ml$/.test(entry)) candidates.push(join(WORKFLOWS_DIR, entry));
  }

  // agentsDir and rulesDir may name the same folder.
  return [...new Set(candidates)].filter((path) =>
    isGenerated(join(root, path)),
  );
}

/**
 * Tells whether a file exists and carries the generated marker where sync writes it.
 *
 * @param path - Absolute path to the file
 * @returns Whether sync wrote it
 */
export function isGenerated(path) {
  if (!existsSync(path)) return false;

  try {
    const line = markerLine(readFileSync(path, 'utf8'));
    return MARKER_STARTS.some((start) => line.startsWith(start));
  } catch {
    return false;
  }
}

/**
 * Tells whether a file on disk holds the given text, whatever its line endings.
 *
 * @param path - The file
 * @param content - The text it should hold
 * @returns True when they match once CRLF is read as LF
 */
export function holds(path, content) {
  return readFileSync(path, 'utf8').replace(/\r\n/g, '\n') === content;
}

/**
 * Finds the line sync puts its marker on: the first, or the first after markdown frontmatter.
 *
 * @param content - The file's text
 * @returns That line, empty when there is none
 */
function markerLine(content) {
  // A checkout with core.autocrlf turns every line ending into CRLF.
  const lines = content.split(/\r?\n/);
  if (lines[0] !== '---') return lines[0];

  const close = lines.indexOf('---', 1);
  if (close === -1) return '';
  return lines.slice(close + 1).find((line) => line !== '') ?? '';
}

/**
 * Lists a directory's entries, or nothing when it does not exist.
 *
 * @param dir - Absolute path to the directory
 * @returns The entry names
 */
function listDir(dir) {
  return existsSync(dir) && statSync(dir).isDirectory() ? readdirSync(dir) : [];
}

/**
 * Writes the planned files and removes generated ones outside the plan.
 *
 * @param root - The repository root
 * @param options - `force` overwrites files that were not generated
 * @returns Repo-relative paths `written`, `unchanged` and `removed`, and `warnings` about packages an enabled skill needs
 * @throws When a planned path holds a hand-written file and `force` is off
 */
export async function sync(root, { force = false } = {}) {
  const config = readConfig(root);
  const files = await plan(root, config);

  const handWritten = files.filter(
    ({ path, seed }) =>
      !seed && existsSync(join(root, path)) && !isGenerated(join(root, path)),
  );
  if (handWritten.length > 0 && !force) {
    throw new Error(
      `These files were not written by skills sync, so it will not overwrite them:\n${handWritten
        .map(({ path }) => `  ${path}`)
        .join('\n')}\nDelete them, or pass --force to replace them.`,
    );
  }

  const result = {
    written: [],
    unchanged: [],
    removed: [],
    warnings: missingPackages(root, config),
  };

  for (const { path, content, seed } of files) {
    const target = join(root, path);

    if (existsSync(target) && (seed || holds(target, content))) {
      result.unchanged.push(path);
      continue;
    }

    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
    result.written.push(path);
  }

  const planned = new Set(files.map(({ path }) => path));

  for (const path of generatedOnDisk(root, config)) {
    if (planned.has(path)) continue;

    rmSync(join(root, path));
    result.removed.push(path);

    const dir = dirname(join(root, path));
    if (
      dirname(dir) === join(root, config.skillsDir) &&
      readdirSync(dir).length === 0
    ) {
      rmdirSync(dir);
    }
  }

  return result;
}

/**
 * Warns about each enabled skill whose package the repository does not depend on.
 *
 * @param root - The repository root
 * @param config - The config from `readConfig`
 * @returns One message per skill, empty when every package is there
 */
function missingPackages(root, config) {
  const needs = Object.keys(config.skills)
    .map((name) => [name, SKILLS[name].requires])
    .filter(([, pkg]) => pkg);
  if (needs.length === 0) return [];

  const installed = installedPackages(root);

  return needs
    .filter(([, pkg]) => !installed.has(pkg))
    .map(
      ([name, pkg]) =>
        `The ${name} skill runs ${pkg}, which this repository does not depend on. The skill is written, but stops at its first step until you run: npm i -D ${pkg}`,
    );
}
