// ============================================================================
// Sync
// ============================================================================
//
// Writes every enabled skill into the repository and removes generated skills
// the config does not name. A file without the generated marker is never
// overwritten or deleted unless forced.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  rmdirSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { readConfig } from './config.mjs';
import { render } from './render.mjs';
import { SKILLS } from './skills.mjs';

const TEMPLATES = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'templates',
);

/** Text every generated file carries, which is how sync recognises its own. */
export const MARKER_TAG = 'Generated by @euanmsm/skills';

const MARKER = `<!-- ${MARKER_TAG} from .devkit/skills.json. Edit that, then run \`npx skills sync\`. -->`;

/**
 * Renders every file the config asks for, without touching the disk.
 *
 * @param root - The repository root
 * @returns One `{ path, content }` per file, `path` relative to the root
 */
export function plan(root) {
  const config = readConfig(root);
  const files = [];

  for (const [name, options] of Object.entries(config.skills)) {
    const skill = SKILLS[name];
    const values = {
      marker: MARKER,
      baseBranch: config.baseBranch,
      ...skill.values(options, root),
    };

    for (const file of skill.files) {
      const template = readFileSync(join(TEMPLATES, file.template), 'utf8');
      files.push({
        path: join(config[file.dir], file.path),
        content: render(template, values),
      });
    }
  }

  return files;
}

/**
 * Lists the generated files already on disk in the configured directories.
 *
 * @param root - The repository root
 * @returns Repo-relative paths of every file carrying the marker
 */
export function generatedOnDisk(root) {
  const { skillsDir, agentsDir } = readConfig(root);
  const candidates = [];

  for (const entry of listDir(join(root, skillsDir))) {
    candidates.push(join(skillsDir, entry, 'SKILL.md'));
  }
  for (const entry of listDir(join(root, agentsDir))) {
    if (entry.endsWith('.md')) candidates.push(join(agentsDir, entry));
  }

  return candidates.filter((path) => isGenerated(join(root, path)));
}

/**
 * Tells whether a file exists and carries the generated marker.
 *
 * @param path - Absolute path to the file
 * @returns Whether sync wrote it
 */
export function isGenerated(path) {
  if (!existsSync(path)) return false;

  try {
    return readFileSync(path, 'utf8').includes(MARKER_TAG);
  } catch {
    return false;
  }
}

/**
 * Lists a directory's entries, or nothing when it does not exist.
 *
 * @param dir - Absolute path to the directory
 * @returns The entry names
 */
function listDir(dir) {
  return existsSync(dir) ? readdirSync(dir) : [];
}

/**
 * Writes the planned files and removes generated ones outside the plan.
 *
 * @param root - The repository root
 * @param options - `force` overwrites files that were not generated
 * @returns Repo-relative paths `written`, `unchanged` and `removed`
 * @throws When a planned path holds a hand-written file and `force` is off
 */
export function sync(root, { force = false } = {}) {
  const files = plan(root);

  const handWritten = files.filter(
    ({ path }) =>
      existsSync(join(root, path)) && !isGenerated(join(root, path)),
  );
  if (handWritten.length > 0 && !force) {
    throw new Error(
      `These files were not written by skills sync, so it will not overwrite them:\n${handWritten
        .map(({ path }) => `  ${path}`)
        .join('\n')}\nDelete them, or pass --force to replace them.`,
    );
  }

  const result = { written: [], unchanged: [], removed: [] };

  for (const { path, content } of files) {
    const target = join(root, path);

    if (existsSync(target) && readFileSync(target, 'utf8') === content) {
      result.unchanged.push(path);
      continue;
    }

    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
    result.written.push(path);
  }

  const planned = new Set(files.map(({ path }) => path));

  for (const path of generatedOnDisk(root)) {
    if (planned.has(path)) continue;

    rmSync(join(root, path));
    result.removed.push(path);

    const dir = dirname(join(root, path));
    if (path.endsWith('SKILL.md') && readdirSync(dir).length === 0) {
      rmdirSync(dir);
    }
  }

  return result;
}
